model:
  class_path: nre.Seq2SeqPTRNREModule
  init_args:
    vocab_file: data/nre/vocab.txt
    label_file: data/nre/relations.txt
    do_lower: false
    embedding_size: 128
    hidden_size: 256
    num_layers: 1
    max_decoder_step: 50